// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: acc.proto

#include "acc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace section {
class login_c2sDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<login_c2s>
      _instance;
} _login_c2s_default_instance_;
class login_s2cDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<login_s2c>
      _instance;
} _login_s2c_default_instance_;
}  // namespace section
namespace protobuf_acc_2eproto {
static void InitDefaultslogin_c2s() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::section::_login_c2s_default_instance_;
    new (ptr) ::section::login_c2s();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::section::login_c2s::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_login_c2s =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultslogin_c2s}, {}};

static void InitDefaultslogin_s2c() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::section::_login_s2c_default_instance_;
    new (ptr) ::section::login_s2c();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::section::login_s2c::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_login_s2c =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultslogin_s2c}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_login_c2s.base);
  ::google::protobuf::internal::InitSCC(&scc_info_login_s2c.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::login_c2s, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::login_c2s, platform_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::login_c2s, game_account_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::login_c2s, game_account_sign_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::login_c2s, channel_open_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::login_c2s, channel_param_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::login_s2c, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::login_s2c, code_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::login_s2c, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::login_s2c, channel_open_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::login_s2c, game_account_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::login_s2c, game_account_sign_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::login_s2c, game_login_key_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::section::login_c2s)},
  { 10, -1, sizeof(::section::login_s2c)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::section::_login_c2s_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::section::_login_s2c_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "acc.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\tacc.proto\022\007section\"\201\001\n\tlogin_c2s\022\020\n\010pl"
      "atform\030\001 \001(\t\022\027\n\017game_account_id\030\002 \001(\t\022\031\n"
      "\021game_account_sign\030\003 \001(\t\022\027\n\017channel_open"
      "_id\030\004 \001(\t\022\025\n\rchannel_param\030\005 \001(\t\"\212\001\n\tlog"
      "in_s2c\022\014\n\004code\030\001 \001(\005\022\n\n\002id\030\002 \001(\005\022\027\n\017chan"
      "nel_open_id\030\003 \001(\t\022\027\n\017game_account_id\030\004 \001"
      "(\t\022\031\n\021game_account_sign\030\005 \001(\t\022\026\n\016game_lo"
      "gin_key\030\006 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 301);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "acc.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_acc_2eproto
namespace section {

// ===================================================================

void login_c2s::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int login_c2s::kPlatformFieldNumber;
const int login_c2s::kGameAccountIdFieldNumber;
const int login_c2s::kGameAccountSignFieldNumber;
const int login_c2s::kChannelOpenIdFieldNumber;
const int login_c2s::kChannelParamFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

login_c2s::login_c2s()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_acc_2eproto::scc_info_login_c2s.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:section.login_c2s)
}
login_c2s::login_c2s(const login_c2s& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  platform_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.platform().size() > 0) {
    platform_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.platform_);
  }
  game_account_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.game_account_id().size() > 0) {
    game_account_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.game_account_id_);
  }
  game_account_sign_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.game_account_sign().size() > 0) {
    game_account_sign_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.game_account_sign_);
  }
  channel_open_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.channel_open_id().size() > 0) {
    channel_open_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.channel_open_id_);
  }
  channel_param_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.channel_param().size() > 0) {
    channel_param_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.channel_param_);
  }
  // @@protoc_insertion_point(copy_constructor:section.login_c2s)
}

void login_c2s::SharedCtor() {
  platform_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_account_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_account_sign_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channel_open_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channel_param_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

login_c2s::~login_c2s() {
  // @@protoc_insertion_point(destructor:section.login_c2s)
  SharedDtor();
}

void login_c2s::SharedDtor() {
  platform_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_account_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_account_sign_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channel_open_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channel_param_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void login_c2s::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* login_c2s::descriptor() {
  ::protobuf_acc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_acc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const login_c2s& login_c2s::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_acc_2eproto::scc_info_login_c2s.base);
  return *internal_default_instance();
}


void login_c2s::Clear() {
// @@protoc_insertion_point(message_clear_start:section.login_c2s)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  platform_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_account_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_account_sign_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channel_open_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channel_param_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool login_c2s::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:section.login_c2s)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string platform = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_platform()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->platform().data(), static_cast<int>(this->platform().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "section.login_c2s.platform"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string game_account_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_game_account_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->game_account_id().data(), static_cast<int>(this->game_account_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "section.login_c2s.game_account_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string game_account_sign = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_game_account_sign()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->game_account_sign().data(), static_cast<int>(this->game_account_sign().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "section.login_c2s.game_account_sign"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string channel_open_id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_channel_open_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->channel_open_id().data(), static_cast<int>(this->channel_open_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "section.login_c2s.channel_open_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string channel_param = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_channel_param()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->channel_param().data(), static_cast<int>(this->channel_param().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "section.login_c2s.channel_param"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:section.login_c2s)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:section.login_c2s)
  return false;
#undef DO_
}

void login_c2s::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:section.login_c2s)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string platform = 1;
  if (this->platform().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->platform().data(), static_cast<int>(this->platform().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_c2s.platform");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->platform(), output);
  }

  // string game_account_id = 2;
  if (this->game_account_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->game_account_id().data(), static_cast<int>(this->game_account_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_c2s.game_account_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->game_account_id(), output);
  }

  // string game_account_sign = 3;
  if (this->game_account_sign().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->game_account_sign().data(), static_cast<int>(this->game_account_sign().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_c2s.game_account_sign");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->game_account_sign(), output);
  }

  // string channel_open_id = 4;
  if (this->channel_open_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->channel_open_id().data(), static_cast<int>(this->channel_open_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_c2s.channel_open_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->channel_open_id(), output);
  }

  // string channel_param = 5;
  if (this->channel_param().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->channel_param().data(), static_cast<int>(this->channel_param().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_c2s.channel_param");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->channel_param(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:section.login_c2s)
}

::google::protobuf::uint8* login_c2s::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:section.login_c2s)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string platform = 1;
  if (this->platform().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->platform().data(), static_cast<int>(this->platform().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_c2s.platform");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->platform(), target);
  }

  // string game_account_id = 2;
  if (this->game_account_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->game_account_id().data(), static_cast<int>(this->game_account_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_c2s.game_account_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->game_account_id(), target);
  }

  // string game_account_sign = 3;
  if (this->game_account_sign().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->game_account_sign().data(), static_cast<int>(this->game_account_sign().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_c2s.game_account_sign");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->game_account_sign(), target);
  }

  // string channel_open_id = 4;
  if (this->channel_open_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->channel_open_id().data(), static_cast<int>(this->channel_open_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_c2s.channel_open_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->channel_open_id(), target);
  }

  // string channel_param = 5;
  if (this->channel_param().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->channel_param().data(), static_cast<int>(this->channel_param().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_c2s.channel_param");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->channel_param(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:section.login_c2s)
  return target;
}

size_t login_c2s::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:section.login_c2s)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string platform = 1;
  if (this->platform().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->platform());
  }

  // string game_account_id = 2;
  if (this->game_account_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->game_account_id());
  }

  // string game_account_sign = 3;
  if (this->game_account_sign().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->game_account_sign());
  }

  // string channel_open_id = 4;
  if (this->channel_open_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->channel_open_id());
  }

  // string channel_param = 5;
  if (this->channel_param().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->channel_param());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void login_c2s::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:section.login_c2s)
  GOOGLE_DCHECK_NE(&from, this);
  const login_c2s* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const login_c2s>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:section.login_c2s)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:section.login_c2s)
    MergeFrom(*source);
  }
}

void login_c2s::MergeFrom(const login_c2s& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:section.login_c2s)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.platform().size() > 0) {

    platform_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.platform_);
  }
  if (from.game_account_id().size() > 0) {

    game_account_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.game_account_id_);
  }
  if (from.game_account_sign().size() > 0) {

    game_account_sign_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.game_account_sign_);
  }
  if (from.channel_open_id().size() > 0) {

    channel_open_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.channel_open_id_);
  }
  if (from.channel_param().size() > 0) {

    channel_param_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.channel_param_);
  }
}

void login_c2s::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:section.login_c2s)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void login_c2s::CopyFrom(const login_c2s& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:section.login_c2s)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool login_c2s::IsInitialized() const {
  return true;
}

void login_c2s::Swap(login_c2s* other) {
  if (other == this) return;
  InternalSwap(other);
}
void login_c2s::InternalSwap(login_c2s* other) {
  using std::swap;
  platform_.Swap(&other->platform_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  game_account_id_.Swap(&other->game_account_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  game_account_sign_.Swap(&other->game_account_sign_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  channel_open_id_.Swap(&other->channel_open_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  channel_param_.Swap(&other->channel_param_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata login_c2s::GetMetadata() const {
  protobuf_acc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_acc_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void login_s2c::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int login_s2c::kCodeFieldNumber;
const int login_s2c::kIdFieldNumber;
const int login_s2c::kChannelOpenIdFieldNumber;
const int login_s2c::kGameAccountIdFieldNumber;
const int login_s2c::kGameAccountSignFieldNumber;
const int login_s2c::kGameLoginKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

login_s2c::login_s2c()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_acc_2eproto::scc_info_login_s2c.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:section.login_s2c)
}
login_s2c::login_s2c(const login_s2c& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  channel_open_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.channel_open_id().size() > 0) {
    channel_open_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.channel_open_id_);
  }
  game_account_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.game_account_id().size() > 0) {
    game_account_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.game_account_id_);
  }
  game_account_sign_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.game_account_sign().size() > 0) {
    game_account_sign_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.game_account_sign_);
  }
  game_login_key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.game_login_key().size() > 0) {
    game_login_key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.game_login_key_);
  }
  ::memcpy(&code_, &from.code_,
    static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&code_)) + sizeof(id_));
  // @@protoc_insertion_point(copy_constructor:section.login_s2c)
}

void login_s2c::SharedCtor() {
  channel_open_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_account_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_account_sign_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_login_key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&code_)) + sizeof(id_));
}

login_s2c::~login_s2c() {
  // @@protoc_insertion_point(destructor:section.login_s2c)
  SharedDtor();
}

void login_s2c::SharedDtor() {
  channel_open_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_account_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_account_sign_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_login_key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void login_s2c::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* login_s2c::descriptor() {
  ::protobuf_acc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_acc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const login_s2c& login_s2c::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_acc_2eproto::scc_info_login_s2c.base);
  return *internal_default_instance();
}


void login_s2c::Clear() {
// @@protoc_insertion_point(message_clear_start:section.login_s2c)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  channel_open_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_account_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_account_sign_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  game_login_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&code_)) + sizeof(id_));
  _internal_metadata_.Clear();
}

bool login_s2c::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:section.login_s2c)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string channel_open_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_channel_open_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->channel_open_id().data(), static_cast<int>(this->channel_open_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "section.login_s2c.channel_open_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string game_account_id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_game_account_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->game_account_id().data(), static_cast<int>(this->game_account_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "section.login_s2c.game_account_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string game_account_sign = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_game_account_sign()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->game_account_sign().data(), static_cast<int>(this->game_account_sign().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "section.login_s2c.game_account_sign"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string game_login_key = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_game_login_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->game_login_key().data(), static_cast<int>(this->game_login_key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "section.login_s2c.game_login_key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:section.login_s2c)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:section.login_s2c)
  return false;
#undef DO_
}

void login_s2c::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:section.login_s2c)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->code(), output);
  }

  // int32 id = 2;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->id(), output);
  }

  // string channel_open_id = 3;
  if (this->channel_open_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->channel_open_id().data(), static_cast<int>(this->channel_open_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_s2c.channel_open_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->channel_open_id(), output);
  }

  // string game_account_id = 4;
  if (this->game_account_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->game_account_id().data(), static_cast<int>(this->game_account_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_s2c.game_account_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->game_account_id(), output);
  }

  // string game_account_sign = 5;
  if (this->game_account_sign().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->game_account_sign().data(), static_cast<int>(this->game_account_sign().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_s2c.game_account_sign");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->game_account_sign(), output);
  }

  // string game_login_key = 6;
  if (this->game_login_key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->game_login_key().data(), static_cast<int>(this->game_login_key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_s2c.game_login_key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->game_login_key(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:section.login_s2c)
}

::google::protobuf::uint8* login_s2c::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:section.login_s2c)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->code(), target);
  }

  // int32 id = 2;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->id(), target);
  }

  // string channel_open_id = 3;
  if (this->channel_open_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->channel_open_id().data(), static_cast<int>(this->channel_open_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_s2c.channel_open_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->channel_open_id(), target);
  }

  // string game_account_id = 4;
  if (this->game_account_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->game_account_id().data(), static_cast<int>(this->game_account_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_s2c.game_account_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->game_account_id(), target);
  }

  // string game_account_sign = 5;
  if (this->game_account_sign().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->game_account_sign().data(), static_cast<int>(this->game_account_sign().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_s2c.game_account_sign");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->game_account_sign(), target);
  }

  // string game_login_key = 6;
  if (this->game_login_key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->game_login_key().data(), static_cast<int>(this->game_login_key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "section.login_s2c.game_login_key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->game_login_key(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:section.login_s2c)
  return target;
}

size_t login_s2c::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:section.login_s2c)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string channel_open_id = 3;
  if (this->channel_open_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->channel_open_id());
  }

  // string game_account_id = 4;
  if (this->game_account_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->game_account_id());
  }

  // string game_account_sign = 5;
  if (this->game_account_sign().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->game_account_sign());
  }

  // string game_login_key = 6;
  if (this->game_login_key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->game_login_key());
  }

  // int32 code = 1;
  if (this->code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->code());
  }

  // int32 id = 2;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void login_s2c::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:section.login_s2c)
  GOOGLE_DCHECK_NE(&from, this);
  const login_s2c* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const login_s2c>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:section.login_s2c)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:section.login_s2c)
    MergeFrom(*source);
  }
}

void login_s2c::MergeFrom(const login_s2c& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:section.login_s2c)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.channel_open_id().size() > 0) {

    channel_open_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.channel_open_id_);
  }
  if (from.game_account_id().size() > 0) {

    game_account_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.game_account_id_);
  }
  if (from.game_account_sign().size() > 0) {

    game_account_sign_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.game_account_sign_);
  }
  if (from.game_login_key().size() > 0) {

    game_login_key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.game_login_key_);
  }
  if (from.code() != 0) {
    set_code(from.code());
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
}

void login_s2c::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:section.login_s2c)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void login_s2c::CopyFrom(const login_s2c& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:section.login_s2c)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool login_s2c::IsInitialized() const {
  return true;
}

void login_s2c::Swap(login_s2c* other) {
  if (other == this) return;
  InternalSwap(other);
}
void login_s2c::InternalSwap(login_s2c* other) {
  using std::swap;
  channel_open_id_.Swap(&other->channel_open_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  game_account_id_.Swap(&other->game_account_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  game_account_sign_.Swap(&other->game_account_sign_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  game_login_key_.Swap(&other->game_login_key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(code_, other->code_);
  swap(id_, other->id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata login_s2c::GetMetadata() const {
  protobuf_acc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_acc_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace section
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::section::login_c2s* Arena::CreateMaybeMessage< ::section::login_c2s >(Arena* arena) {
  return Arena::CreateInternal< ::section::login_c2s >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::section::login_s2c* Arena::CreateMaybeMessage< ::section::login_s2c >(Arena* arena) {
  return Arena::CreateInternal< ::section::login_s2c >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
