// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NullPmd.proto

#ifndef PROTOBUF_INCLUDED_NullPmd_2eproto
#define PROTOBUF_INCLUDED_NullPmd_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_NullPmd_2eproto 

namespace protobuf_NullPmd_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_NullPmd_2eproto
namespace PlatPmd {
class NetPackageNullPmd_C2S;
class NetPackageNullPmd_C2SDefaultTypeInternal;
extern NetPackageNullPmd_C2SDefaultTypeInternal _NetPackageNullPmd_C2S_default_instance_;
class NetTickNullPmd_SC;
class NetTickNullPmd_SCDefaultTypeInternal;
extern NetTickNullPmd_SCDefaultTypeInternal _NetTickNullPmd_SC_default_instance_;
class NullPmd;
class NullPmdDefaultTypeInternal;
extern NullPmdDefaultTypeInternal _NullPmd_default_instance_;
}  // namespace PlatPmd
namespace google {
namespace protobuf {
template<> ::PlatPmd::NetPackageNullPmd_C2S* Arena::CreateMaybeMessage<::PlatPmd::NetPackageNullPmd_C2S>(Arena*);
template<> ::PlatPmd::NetTickNullPmd_SC* Arena::CreateMaybeMessage<::PlatPmd::NetTickNullPmd_SC>(Arena*);
template<> ::PlatPmd::NullPmd* Arena::CreateMaybeMessage<::PlatPmd::NullPmd>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace PlatPmd {

enum NullPmd_Param {
  NullPmd_Param_NetPackageNullPmd_C2S = 0,
  NullPmd_Param_NetTickNullPmd_S2C = 1,
  NullPmd_Param_NullPmd_Param_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  NullPmd_Param_NullPmd_Param_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool NullPmd_Param_IsValid(int value);
const NullPmd_Param NullPmd_Param_Param_MIN = NullPmd_Param_NetPackageNullPmd_C2S;
const NullPmd_Param NullPmd_Param_Param_MAX = NullPmd_Param_NetTickNullPmd_S2C;
const int NullPmd_Param_Param_ARRAYSIZE = NullPmd_Param_Param_MAX + 1;

const ::google::protobuf::EnumDescriptor* NullPmd_Param_descriptor();
inline const ::std::string& NullPmd_Param_Name(NullPmd_Param value) {
  return ::google::protobuf::internal::NameOfEnum(
    NullPmd_Param_descriptor(), value);
}
inline bool NullPmd_Param_Parse(
    const ::std::string& name, NullPmd_Param* value) {
  return ::google::protobuf::internal::ParseNamedEnum<NullPmd_Param>(
    NullPmd_Param_descriptor(), name, value);
}
// ===================================================================

class NullPmd : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PlatPmd.NullPmd) */ {
 public:
  NullPmd();
  virtual ~NullPmd();

  NullPmd(const NullPmd& from);

  inline NullPmd& operator=(const NullPmd& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NullPmd(NullPmd&& from) noexcept
    : NullPmd() {
    *this = ::std::move(from);
  }

  inline NullPmd& operator=(NullPmd&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NullPmd& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NullPmd* internal_default_instance() {
    return reinterpret_cast<const NullPmd*>(
               &_NullPmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(NullPmd* other);
  friend void swap(NullPmd& a, NullPmd& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NullPmd* New() const final {
    return CreateMaybeMessage<NullPmd>(NULL);
  }

  NullPmd* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NullPmd>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NullPmd& from);
  void MergeFrom(const NullPmd& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NullPmd* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef NullPmd_Param Param;
  static const Param NetPackageNullPmd_C2S =
    NullPmd_Param_NetPackageNullPmd_C2S;
  static const Param NetTickNullPmd_S2C =
    NullPmd_Param_NetTickNullPmd_S2C;
  static inline bool Param_IsValid(int value) {
    return NullPmd_Param_IsValid(value);
  }
  static const Param Param_MIN =
    NullPmd_Param_Param_MIN;
  static const Param Param_MAX =
    NullPmd_Param_Param_MAX;
  static const int Param_ARRAYSIZE =
    NullPmd_Param_Param_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Param_descriptor() {
    return NullPmd_Param_descriptor();
  }
  static inline const ::std::string& Param_Name(Param value) {
    return NullPmd_Param_Name(value);
  }
  static inline bool Param_Parse(const ::std::string& name,
      Param* value) {
    return NullPmd_Param_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:PlatPmd.NullPmd)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_NullPmd_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NetPackageNullPmd_C2S : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PlatPmd.NetPackageNullPmd_C2S) */ {
 public:
  NetPackageNullPmd_C2S();
  virtual ~NetPackageNullPmd_C2S();

  NetPackageNullPmd_C2S(const NetPackageNullPmd_C2S& from);

  inline NetPackageNullPmd_C2S& operator=(const NetPackageNullPmd_C2S& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NetPackageNullPmd_C2S(NetPackageNullPmd_C2S&& from) noexcept
    : NetPackageNullPmd_C2S() {
    *this = ::std::move(from);
  }

  inline NetPackageNullPmd_C2S& operator=(NetPackageNullPmd_C2S&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NetPackageNullPmd_C2S& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NetPackageNullPmd_C2S* internal_default_instance() {
    return reinterpret_cast<const NetPackageNullPmd_C2S*>(
               &_NetPackageNullPmd_C2S_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(NetPackageNullPmd_C2S* other);
  friend void swap(NetPackageNullPmd_C2S& a, NetPackageNullPmd_C2S& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NetPackageNullPmd_C2S* New() const final {
    return CreateMaybeMessage<NetPackageNullPmd_C2S>(NULL);
  }

  NetPackageNullPmd_C2S* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NetPackageNullPmd_C2S>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NetPackageNullPmd_C2S& from);
  void MergeFrom(const NetPackageNullPmd_C2S& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NetPackageNullPmd_C2S* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes data = 5;
  void clear_data();
  static const int kDataFieldNumber = 5;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // int32 byCmd = 1;
  void clear_bycmd();
  static const int kByCmdFieldNumber = 1;
  ::google::protobuf::int32 bycmd() const;
  void set_bycmd(::google::protobuf::int32 value);

  // int32 byParam = 2;
  void clear_byparam();
  static const int kByParamFieldNumber = 2;
  ::google::protobuf::int32 byparam() const;
  void set_byparam(::google::protobuf::int32 value);

  // int64 fid = 4;
  void clear_fid();
  static const int kFidFieldNumber = 4;
  ::google::protobuf::int64 fid() const;
  void set_fid(::google::protobuf::int64 value);

  // int32 seq = 3;
  void clear_seq();
  static const int kSeqFieldNumber = 3;
  ::google::protobuf::int32 seq() const;
  void set_seq(::google::protobuf::int32 value);

  // int32 bitmask = 7;
  void clear_bitmask();
  static const int kBitmaskFieldNumber = 7;
  ::google::protobuf::int32 bitmask() const;
  void set_bitmask(::google::protobuf::int32 value);

  // int64 prototype = 6;
  void clear_prototype();
  static const int kPrototypeFieldNumber = 6;
  ::google::protobuf::int64 prototype() const;
  void set_prototype(::google::protobuf::int64 value);

  // int32 time = 8;
  void clear_time();
  static const int kTimeFieldNumber = 8;
  ::google::protobuf::int32 time() const;
  void set_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PlatPmd.NetPackageNullPmd_C2S)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::int32 bycmd_;
  ::google::protobuf::int32 byparam_;
  ::google::protobuf::int64 fid_;
  ::google::protobuf::int32 seq_;
  ::google::protobuf::int32 bitmask_;
  ::google::protobuf::int64 prototype_;
  ::google::protobuf::int32 time_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_NullPmd_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NetTickNullPmd_SC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PlatPmd.NetTickNullPmd_SC) */ {
 public:
  NetTickNullPmd_SC();
  virtual ~NetTickNullPmd_SC();

  NetTickNullPmd_SC(const NetTickNullPmd_SC& from);

  inline NetTickNullPmd_SC& operator=(const NetTickNullPmd_SC& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NetTickNullPmd_SC(NetTickNullPmd_SC&& from) noexcept
    : NetTickNullPmd_SC() {
    *this = ::std::move(from);
  }

  inline NetTickNullPmd_SC& operator=(NetTickNullPmd_SC&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NetTickNullPmd_SC& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NetTickNullPmd_SC* internal_default_instance() {
    return reinterpret_cast<const NetTickNullPmd_SC*>(
               &_NetTickNullPmd_SC_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(NetTickNullPmd_SC* other);
  friend void swap(NetTickNullPmd_SC& a, NetTickNullPmd_SC& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NetTickNullPmd_SC* New() const final {
    return CreateMaybeMessage<NetTickNullPmd_SC>(NULL);
  }

  NetTickNullPmd_SC* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NetTickNullPmd_SC>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NetTickNullPmd_SC& from);
  void MergeFrom(const NetTickNullPmd_SC& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NetTickNullPmd_SC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 requesttime = 1;
  void clear_requesttime();
  static const int kRequesttimeFieldNumber = 1;
  ::google::protobuf::int32 requesttime() const;
  void set_requesttime(::google::protobuf::int32 value);

  // int32 mytime = 2;
  void clear_mytime();
  static const int kMytimeFieldNumber = 2;
  ::google::protobuf::int32 mytime() const;
  void set_mytime(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PlatPmd.NetTickNullPmd_SC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 requesttime_;
  ::google::protobuf::int32 mytime_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_NullPmd_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NullPmd

// -------------------------------------------------------------------

// NetPackageNullPmd_C2S

// int32 byCmd = 1;
inline void NetPackageNullPmd_C2S::clear_bycmd() {
  bycmd_ = 0;
}
inline ::google::protobuf::int32 NetPackageNullPmd_C2S::bycmd() const {
  // @@protoc_insertion_point(field_get:PlatPmd.NetPackageNullPmd_C2S.byCmd)
  return bycmd_;
}
inline void NetPackageNullPmd_C2S::set_bycmd(::google::protobuf::int32 value) {
  
  bycmd_ = value;
  // @@protoc_insertion_point(field_set:PlatPmd.NetPackageNullPmd_C2S.byCmd)
}

// int32 byParam = 2;
inline void NetPackageNullPmd_C2S::clear_byparam() {
  byparam_ = 0;
}
inline ::google::protobuf::int32 NetPackageNullPmd_C2S::byparam() const {
  // @@protoc_insertion_point(field_get:PlatPmd.NetPackageNullPmd_C2S.byParam)
  return byparam_;
}
inline void NetPackageNullPmd_C2S::set_byparam(::google::protobuf::int32 value) {
  
  byparam_ = value;
  // @@protoc_insertion_point(field_set:PlatPmd.NetPackageNullPmd_C2S.byParam)
}

// int32 seq = 3;
inline void NetPackageNullPmd_C2S::clear_seq() {
  seq_ = 0;
}
inline ::google::protobuf::int32 NetPackageNullPmd_C2S::seq() const {
  // @@protoc_insertion_point(field_get:PlatPmd.NetPackageNullPmd_C2S.seq)
  return seq_;
}
inline void NetPackageNullPmd_C2S::set_seq(::google::protobuf::int32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:PlatPmd.NetPackageNullPmd_C2S.seq)
}

// int64 fid = 4;
inline void NetPackageNullPmd_C2S::clear_fid() {
  fid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 NetPackageNullPmd_C2S::fid() const {
  // @@protoc_insertion_point(field_get:PlatPmd.NetPackageNullPmd_C2S.fid)
  return fid_;
}
inline void NetPackageNullPmd_C2S::set_fid(::google::protobuf::int64 value) {
  
  fid_ = value;
  // @@protoc_insertion_point(field_set:PlatPmd.NetPackageNullPmd_C2S.fid)
}

// bytes data = 5;
inline void NetPackageNullPmd_C2S::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NetPackageNullPmd_C2S::data() const {
  // @@protoc_insertion_point(field_get:PlatPmd.NetPackageNullPmd_C2S.data)
  return data_.GetNoArena();
}
inline void NetPackageNullPmd_C2S::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PlatPmd.NetPackageNullPmd_C2S.data)
}
#if LANG_CXX11
inline void NetPackageNullPmd_C2S::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PlatPmd.NetPackageNullPmd_C2S.data)
}
#endif
inline void NetPackageNullPmd_C2S::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PlatPmd.NetPackageNullPmd_C2S.data)
}
inline void NetPackageNullPmd_C2S::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PlatPmd.NetPackageNullPmd_C2S.data)
}
inline ::std::string* NetPackageNullPmd_C2S::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:PlatPmd.NetPackageNullPmd_C2S.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NetPackageNullPmd_C2S::release_data() {
  // @@protoc_insertion_point(field_release:PlatPmd.NetPackageNullPmd_C2S.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NetPackageNullPmd_C2S::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:PlatPmd.NetPackageNullPmd_C2S.data)
}

// int64 prototype = 6;
inline void NetPackageNullPmd_C2S::clear_prototype() {
  prototype_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 NetPackageNullPmd_C2S::prototype() const {
  // @@protoc_insertion_point(field_get:PlatPmd.NetPackageNullPmd_C2S.prototype)
  return prototype_;
}
inline void NetPackageNullPmd_C2S::set_prototype(::google::protobuf::int64 value) {
  
  prototype_ = value;
  // @@protoc_insertion_point(field_set:PlatPmd.NetPackageNullPmd_C2S.prototype)
}

// int32 bitmask = 7;
inline void NetPackageNullPmd_C2S::clear_bitmask() {
  bitmask_ = 0;
}
inline ::google::protobuf::int32 NetPackageNullPmd_C2S::bitmask() const {
  // @@protoc_insertion_point(field_get:PlatPmd.NetPackageNullPmd_C2S.bitmask)
  return bitmask_;
}
inline void NetPackageNullPmd_C2S::set_bitmask(::google::protobuf::int32 value) {
  
  bitmask_ = value;
  // @@protoc_insertion_point(field_set:PlatPmd.NetPackageNullPmd_C2S.bitmask)
}

// int32 time = 8;
inline void NetPackageNullPmd_C2S::clear_time() {
  time_ = 0;
}
inline ::google::protobuf::int32 NetPackageNullPmd_C2S::time() const {
  // @@protoc_insertion_point(field_get:PlatPmd.NetPackageNullPmd_C2S.time)
  return time_;
}
inline void NetPackageNullPmd_C2S::set_time(::google::protobuf::int32 value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:PlatPmd.NetPackageNullPmd_C2S.time)
}

// -------------------------------------------------------------------

// NetTickNullPmd_SC

// int32 requesttime = 1;
inline void NetTickNullPmd_SC::clear_requesttime() {
  requesttime_ = 0;
}
inline ::google::protobuf::int32 NetTickNullPmd_SC::requesttime() const {
  // @@protoc_insertion_point(field_get:PlatPmd.NetTickNullPmd_SC.requesttime)
  return requesttime_;
}
inline void NetTickNullPmd_SC::set_requesttime(::google::protobuf::int32 value) {
  
  requesttime_ = value;
  // @@protoc_insertion_point(field_set:PlatPmd.NetTickNullPmd_SC.requesttime)
}

// int32 mytime = 2;
inline void NetTickNullPmd_SC::clear_mytime() {
  mytime_ = 0;
}
inline ::google::protobuf::int32 NetTickNullPmd_SC::mytime() const {
  // @@protoc_insertion_point(field_get:PlatPmd.NetTickNullPmd_SC.mytime)
  return mytime_;
}
inline void NetTickNullPmd_SC::set_mytime(::google::protobuf::int32 value) {
  
  mytime_ = value;
  // @@protoc_insertion_point(field_set:PlatPmd.NetTickNullPmd_SC.mytime)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace PlatPmd

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::PlatPmd::NullPmd_Param> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PlatPmd::NullPmd_Param>() {
  return ::PlatPmd::NullPmd_Param_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_NullPmd_2eproto
