// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NullPmd.proto

#include "NullPmd.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace PlatPmd {
class NullPmdDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NullPmd>
      _instance;
} _NullPmd_default_instance_;
class NetPackageNullPmd_C2SDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NetPackageNullPmd_C2S>
      _instance;
} _NetPackageNullPmd_C2S_default_instance_;
class NetTickNullPmd_SCDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NetTickNullPmd_SC>
      _instance;
} _NetTickNullPmd_SC_default_instance_;
}  // namespace PlatPmd
namespace protobuf_NullPmd_2eproto {
static void InitDefaultsNullPmd() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::PlatPmd::_NullPmd_default_instance_;
    new (ptr) ::PlatPmd::NullPmd();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PlatPmd::NullPmd::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NullPmd =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNullPmd}, {}};

static void InitDefaultsNetPackageNullPmd_C2S() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::PlatPmd::_NetPackageNullPmd_C2S_default_instance_;
    new (ptr) ::PlatPmd::NetPackageNullPmd_C2S();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PlatPmd::NetPackageNullPmd_C2S::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NetPackageNullPmd_C2S =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNetPackageNullPmd_C2S}, {}};

static void InitDefaultsNetTickNullPmd_SC() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::PlatPmd::_NetTickNullPmd_SC_default_instance_;
    new (ptr) ::PlatPmd::NetTickNullPmd_SC();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PlatPmd::NetTickNullPmd_SC::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NetTickNullPmd_SC =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNetTickNullPmd_SC}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_NullPmd.base);
  ::google::protobuf::internal::InitSCC(&scc_info_NetPackageNullPmd_C2S.base);
  ::google::protobuf::internal::InitSCC(&scc_info_NetTickNullPmd_SC.base);
}

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::NullPmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::NetPackageNullPmd_C2S, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::NetPackageNullPmd_C2S, bycmd_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::NetPackageNullPmd_C2S, byparam_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::NetPackageNullPmd_C2S, seq_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::NetPackageNullPmd_C2S, fid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::NetPackageNullPmd_C2S, data_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::NetPackageNullPmd_C2S, prototype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::NetPackageNullPmd_C2S, bitmask_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::NetPackageNullPmd_C2S, time_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::NetTickNullPmd_SC, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::NetTickNullPmd_SC, requesttime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::NetTickNullPmd_SC, mytime_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::PlatPmd::NullPmd)},
  { 5, -1, sizeof(::PlatPmd::NetPackageNullPmd_C2S)},
  { 18, -1, sizeof(::PlatPmd::NetTickNullPmd_SC)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::PlatPmd::_NullPmd_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::PlatPmd::_NetPackageNullPmd_C2S_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::PlatPmd::_NetTickNullPmd_SC_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "NullPmd.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rNullPmd.proto\022\007PlatPmd\"E\n\007NullPmd\":\n\005P"
      "aram\022\031\n\025NetPackageNullPmd_C2S\020\000\022\026\n\022NetTi"
      "ckNullPmd_S2C\020\001\"\221\001\n\025NetPackageNullPmd_C2"
      "S\022\r\n\005byCmd\030\001 \001(\005\022\017\n\007byParam\030\002 \001(\005\022\013\n\003seq"
      "\030\003 \001(\005\022\013\n\003fid\030\004 \001(\003\022\014\n\004data\030\005 \001(\014\022\021\n\tpro"
      "totype\030\006 \001(\003\022\017\n\007bitmask\030\007 \001(\005\022\014\n\004time\030\010 "
      "\001(\005\"8\n\021NetTickNullPmd_SC\022\023\n\013requesttime\030"
      "\001 \001(\005\022\016\n\006mytime\030\002 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 309);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "NullPmd.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_NullPmd_2eproto
namespace PlatPmd {
const ::google::protobuf::EnumDescriptor* NullPmd_Param_descriptor() {
  protobuf_NullPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_NullPmd_2eproto::file_level_enum_descriptors[0];
}
bool NullPmd_Param_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const NullPmd_Param NullPmd::NetPackageNullPmd_C2S;
const NullPmd_Param NullPmd::NetTickNullPmd_S2C;
const NullPmd_Param NullPmd::Param_MIN;
const NullPmd_Param NullPmd::Param_MAX;
const int NullPmd::Param_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void NullPmd::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NullPmd::NullPmd()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_NullPmd_2eproto::scc_info_NullPmd.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:PlatPmd.NullPmd)
}
NullPmd::NullPmd(const NullPmd& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:PlatPmd.NullPmd)
}

void NullPmd::SharedCtor() {
}

NullPmd::~NullPmd() {
  // @@protoc_insertion_point(destructor:PlatPmd.NullPmd)
  SharedDtor();
}

void NullPmd::SharedDtor() {
}

void NullPmd::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NullPmd::descriptor() {
  ::protobuf_NullPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NullPmd_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NullPmd& NullPmd::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_NullPmd_2eproto::scc_info_NullPmd.base);
  return *internal_default_instance();
}


void NullPmd::Clear() {
// @@protoc_insertion_point(message_clear_start:PlatPmd.NullPmd)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool NullPmd::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PlatPmd.NullPmd)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:PlatPmd.NullPmd)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PlatPmd.NullPmd)
  return false;
#undef DO_
}

void NullPmd::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PlatPmd.NullPmd)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PlatPmd.NullPmd)
}

::google::protobuf::uint8* NullPmd::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PlatPmd.NullPmd)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PlatPmd.NullPmd)
  return target;
}

size_t NullPmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PlatPmd.NullPmd)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NullPmd::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PlatPmd.NullPmd)
  GOOGLE_DCHECK_NE(&from, this);
  const NullPmd* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NullPmd>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PlatPmd.NullPmd)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PlatPmd.NullPmd)
    MergeFrom(*source);
  }
}

void NullPmd::MergeFrom(const NullPmd& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PlatPmd.NullPmd)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void NullPmd::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PlatPmd.NullPmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NullPmd::CopyFrom(const NullPmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PlatPmd.NullPmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NullPmd::IsInitialized() const {
  return true;
}

void NullPmd::Swap(NullPmd* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NullPmd::InternalSwap(NullPmd* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NullPmd::GetMetadata() const {
  protobuf_NullPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NullPmd_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void NetPackageNullPmd_C2S::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NetPackageNullPmd_C2S::kByCmdFieldNumber;
const int NetPackageNullPmd_C2S::kByParamFieldNumber;
const int NetPackageNullPmd_C2S::kSeqFieldNumber;
const int NetPackageNullPmd_C2S::kFidFieldNumber;
const int NetPackageNullPmd_C2S::kDataFieldNumber;
const int NetPackageNullPmd_C2S::kPrototypeFieldNumber;
const int NetPackageNullPmd_C2S::kBitmaskFieldNumber;
const int NetPackageNullPmd_C2S::kTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NetPackageNullPmd_C2S::NetPackageNullPmd_C2S()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_NullPmd_2eproto::scc_info_NetPackageNullPmd_C2S.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:PlatPmd.NetPackageNullPmd_C2S)
}
NetPackageNullPmd_C2S::NetPackageNullPmd_C2S(const NetPackageNullPmd_C2S& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.data().size() > 0) {
    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  ::memcpy(&bycmd_, &from.bycmd_,
    static_cast<size_t>(reinterpret_cast<char*>(&time_) -
    reinterpret_cast<char*>(&bycmd_)) + sizeof(time_));
  // @@protoc_insertion_point(copy_constructor:PlatPmd.NetPackageNullPmd_C2S)
}

void NetPackageNullPmd_C2S::SharedCtor() {
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&bycmd_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&time_) -
      reinterpret_cast<char*>(&bycmd_)) + sizeof(time_));
}

NetPackageNullPmd_C2S::~NetPackageNullPmd_C2S() {
  // @@protoc_insertion_point(destructor:PlatPmd.NetPackageNullPmd_C2S)
  SharedDtor();
}

void NetPackageNullPmd_C2S::SharedDtor() {
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void NetPackageNullPmd_C2S::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NetPackageNullPmd_C2S::descriptor() {
  ::protobuf_NullPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NullPmd_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NetPackageNullPmd_C2S& NetPackageNullPmd_C2S::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_NullPmd_2eproto::scc_info_NetPackageNullPmd_C2S.base);
  return *internal_default_instance();
}


void NetPackageNullPmd_C2S::Clear() {
// @@protoc_insertion_point(message_clear_start:PlatPmd.NetPackageNullPmd_C2S)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&bycmd_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&time_) -
      reinterpret_cast<char*>(&bycmd_)) + sizeof(time_));
  _internal_metadata_.Clear();
}

bool NetPackageNullPmd_C2S::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PlatPmd.NetPackageNullPmd_C2S)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 byCmd = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &bycmd_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 byParam = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &byparam_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 seq = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &seq_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 fid = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &fid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes data = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 prototype = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &prototype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 bitmask = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &bitmask_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 time = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PlatPmd.NetPackageNullPmd_C2S)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PlatPmd.NetPackageNullPmd_C2S)
  return false;
#undef DO_
}

void NetPackageNullPmd_C2S::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PlatPmd.NetPackageNullPmd_C2S)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 byCmd = 1;
  if (this->bycmd() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->bycmd(), output);
  }

  // int32 byParam = 2;
  if (this->byparam() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->byparam(), output);
  }

  // int32 seq = 3;
  if (this->seq() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->seq(), output);
  }

  // int64 fid = 4;
  if (this->fid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->fid(), output);
  }

  // bytes data = 5;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->data(), output);
  }

  // int64 prototype = 6;
  if (this->prototype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(6, this->prototype(), output);
  }

  // int32 bitmask = 7;
  if (this->bitmask() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->bitmask(), output);
  }

  // int32 time = 8;
  if (this->time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->time(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PlatPmd.NetPackageNullPmd_C2S)
}

::google::protobuf::uint8* NetPackageNullPmd_C2S::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PlatPmd.NetPackageNullPmd_C2S)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 byCmd = 1;
  if (this->bycmd() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->bycmd(), target);
  }

  // int32 byParam = 2;
  if (this->byparam() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->byparam(), target);
  }

  // int32 seq = 3;
  if (this->seq() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->seq(), target);
  }

  // int64 fid = 4;
  if (this->fid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->fid(), target);
  }

  // bytes data = 5;
  if (this->data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->data(), target);
  }

  // int64 prototype = 6;
  if (this->prototype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(6, this->prototype(), target);
  }

  // int32 bitmask = 7;
  if (this->bitmask() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->bitmask(), target);
  }

  // int32 time = 8;
  if (this->time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->time(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PlatPmd.NetPackageNullPmd_C2S)
  return target;
}

size_t NetPackageNullPmd_C2S::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PlatPmd.NetPackageNullPmd_C2S)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes data = 5;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->data());
  }

  // int32 byCmd = 1;
  if (this->bycmd() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->bycmd());
  }

  // int32 byParam = 2;
  if (this->byparam() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->byparam());
  }

  // int64 fid = 4;
  if (this->fid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->fid());
  }

  // int32 seq = 3;
  if (this->seq() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->seq());
  }

  // int32 bitmask = 7;
  if (this->bitmask() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->bitmask());
  }

  // int64 prototype = 6;
  if (this->prototype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->prototype());
  }

  // int32 time = 8;
  if (this->time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->time());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NetPackageNullPmd_C2S::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PlatPmd.NetPackageNullPmd_C2S)
  GOOGLE_DCHECK_NE(&from, this);
  const NetPackageNullPmd_C2S* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NetPackageNullPmd_C2S>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PlatPmd.NetPackageNullPmd_C2S)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PlatPmd.NetPackageNullPmd_C2S)
    MergeFrom(*source);
  }
}

void NetPackageNullPmd_C2S::MergeFrom(const NetPackageNullPmd_C2S& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PlatPmd.NetPackageNullPmd_C2S)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.data().size() > 0) {

    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  if (from.bycmd() != 0) {
    set_bycmd(from.bycmd());
  }
  if (from.byparam() != 0) {
    set_byparam(from.byparam());
  }
  if (from.fid() != 0) {
    set_fid(from.fid());
  }
  if (from.seq() != 0) {
    set_seq(from.seq());
  }
  if (from.bitmask() != 0) {
    set_bitmask(from.bitmask());
  }
  if (from.prototype() != 0) {
    set_prototype(from.prototype());
  }
  if (from.time() != 0) {
    set_time(from.time());
  }
}

void NetPackageNullPmd_C2S::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PlatPmd.NetPackageNullPmd_C2S)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NetPackageNullPmd_C2S::CopyFrom(const NetPackageNullPmd_C2S& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PlatPmd.NetPackageNullPmd_C2S)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NetPackageNullPmd_C2S::IsInitialized() const {
  return true;
}

void NetPackageNullPmd_C2S::Swap(NetPackageNullPmd_C2S* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NetPackageNullPmd_C2S::InternalSwap(NetPackageNullPmd_C2S* other) {
  using std::swap;
  data_.Swap(&other->data_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(bycmd_, other->bycmd_);
  swap(byparam_, other->byparam_);
  swap(fid_, other->fid_);
  swap(seq_, other->seq_);
  swap(bitmask_, other->bitmask_);
  swap(prototype_, other->prototype_);
  swap(time_, other->time_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NetPackageNullPmd_C2S::GetMetadata() const {
  protobuf_NullPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NullPmd_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void NetTickNullPmd_SC::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NetTickNullPmd_SC::kRequesttimeFieldNumber;
const int NetTickNullPmd_SC::kMytimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NetTickNullPmd_SC::NetTickNullPmd_SC()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_NullPmd_2eproto::scc_info_NetTickNullPmd_SC.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:PlatPmd.NetTickNullPmd_SC)
}
NetTickNullPmd_SC::NetTickNullPmd_SC(const NetTickNullPmd_SC& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&requesttime_, &from.requesttime_,
    static_cast<size_t>(reinterpret_cast<char*>(&mytime_) -
    reinterpret_cast<char*>(&requesttime_)) + sizeof(mytime_));
  // @@protoc_insertion_point(copy_constructor:PlatPmd.NetTickNullPmd_SC)
}

void NetTickNullPmd_SC::SharedCtor() {
  ::memset(&requesttime_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&mytime_) -
      reinterpret_cast<char*>(&requesttime_)) + sizeof(mytime_));
}

NetTickNullPmd_SC::~NetTickNullPmd_SC() {
  // @@protoc_insertion_point(destructor:PlatPmd.NetTickNullPmd_SC)
  SharedDtor();
}

void NetTickNullPmd_SC::SharedDtor() {
}

void NetTickNullPmd_SC::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NetTickNullPmd_SC::descriptor() {
  ::protobuf_NullPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NullPmd_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NetTickNullPmd_SC& NetTickNullPmd_SC::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_NullPmd_2eproto::scc_info_NetTickNullPmd_SC.base);
  return *internal_default_instance();
}


void NetTickNullPmd_SC::Clear() {
// @@protoc_insertion_point(message_clear_start:PlatPmd.NetTickNullPmd_SC)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&requesttime_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&mytime_) -
      reinterpret_cast<char*>(&requesttime_)) + sizeof(mytime_));
  _internal_metadata_.Clear();
}

bool NetTickNullPmd_SC::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PlatPmd.NetTickNullPmd_SC)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 requesttime = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &requesttime_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 mytime = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mytime_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PlatPmd.NetTickNullPmd_SC)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PlatPmd.NetTickNullPmd_SC)
  return false;
#undef DO_
}

void NetTickNullPmd_SC::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PlatPmd.NetTickNullPmd_SC)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 requesttime = 1;
  if (this->requesttime() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->requesttime(), output);
  }

  // int32 mytime = 2;
  if (this->mytime() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->mytime(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PlatPmd.NetTickNullPmd_SC)
}

::google::protobuf::uint8* NetTickNullPmd_SC::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PlatPmd.NetTickNullPmd_SC)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 requesttime = 1;
  if (this->requesttime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->requesttime(), target);
  }

  // int32 mytime = 2;
  if (this->mytime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->mytime(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PlatPmd.NetTickNullPmd_SC)
  return target;
}

size_t NetTickNullPmd_SC::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PlatPmd.NetTickNullPmd_SC)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 requesttime = 1;
  if (this->requesttime() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->requesttime());
  }

  // int32 mytime = 2;
  if (this->mytime() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->mytime());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NetTickNullPmd_SC::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PlatPmd.NetTickNullPmd_SC)
  GOOGLE_DCHECK_NE(&from, this);
  const NetTickNullPmd_SC* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NetTickNullPmd_SC>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PlatPmd.NetTickNullPmd_SC)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PlatPmd.NetTickNullPmd_SC)
    MergeFrom(*source);
  }
}

void NetTickNullPmd_SC::MergeFrom(const NetTickNullPmd_SC& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PlatPmd.NetTickNullPmd_SC)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.requesttime() != 0) {
    set_requesttime(from.requesttime());
  }
  if (from.mytime() != 0) {
    set_mytime(from.mytime());
  }
}

void NetTickNullPmd_SC::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PlatPmd.NetTickNullPmd_SC)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NetTickNullPmd_SC::CopyFrom(const NetTickNullPmd_SC& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PlatPmd.NetTickNullPmd_SC)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NetTickNullPmd_SC::IsInitialized() const {
  return true;
}

void NetTickNullPmd_SC::Swap(NetTickNullPmd_SC* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NetTickNullPmd_SC::InternalSwap(NetTickNullPmd_SC* other) {
  using std::swap;
  swap(requesttime_, other->requesttime_);
  swap(mytime_, other->mytime_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NetTickNullPmd_SC::GetMetadata() const {
  protobuf_NullPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NullPmd_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace PlatPmd
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::PlatPmd::NullPmd* Arena::CreateMaybeMessage< ::PlatPmd::NullPmd >(Arena* arena) {
  return Arena::CreateInternal< ::PlatPmd::NullPmd >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::PlatPmd::NetPackageNullPmd_C2S* Arena::CreateMaybeMessage< ::PlatPmd::NetPackageNullPmd_C2S >(Arena* arena) {
  return Arena::CreateInternal< ::PlatPmd::NetPackageNullPmd_C2S >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::PlatPmd::NetTickNullPmd_SC* Arena::CreateMaybeMessage< ::PlatPmd::NetTickNullPmd_SC >(Arena* arena) {
  return Arena::CreateInternal< ::PlatPmd::NetTickNullPmd_SC >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
