// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerPmd.proto

#include "PlayerPmd.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_Types_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_Types_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_P_Player;
}  // namespace protobuf_Types_2eproto
namespace PlatPmd {
class PlayerPmdDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PlayerPmd>
      _instance;
} _PlayerPmd_default_instance_;
class SelfInfoPlayerPmd_C2SDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SelfInfoPlayerPmd_C2S>
      _instance;
} _SelfInfoPlayerPmd_C2S_default_instance_;
}  // namespace PlatPmd
namespace protobuf_PlayerPmd_2eproto {
static void InitDefaultsPlayerPmd() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::PlatPmd::_PlayerPmd_default_instance_;
    new (ptr) ::PlatPmd::PlayerPmd();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PlatPmd::PlayerPmd::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PlayerPmd =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPlayerPmd}, {}};

static void InitDefaultsSelfInfoPlayerPmd_C2S() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::PlatPmd::_SelfInfoPlayerPmd_C2S_default_instance_;
    new (ptr) ::PlatPmd::SelfInfoPlayerPmd_C2S();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PlatPmd::SelfInfoPlayerPmd_C2S::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_SelfInfoPlayerPmd_C2S =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsSelfInfoPlayerPmd_C2S}, {
      &protobuf_Types_2eproto::scc_info_P_Player.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_PlayerPmd.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SelfInfoPlayerPmd_C2S.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::PlayerPmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::SelfInfoPlayerPmd_C2S, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PlatPmd::SelfInfoPlayerPmd_C2S, player_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::PlatPmd::PlayerPmd)},
  { 5, -1, sizeof(::PlatPmd::SelfInfoPlayerPmd_C2S)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::PlatPmd::_PlayerPmd_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::PlatPmd::_SelfInfoPlayerPmd_C2S_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "PlayerPmd.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017PlayerPmd.proto\022\007PlatPmd\032\013Types.proto\""
      "/\n\tPlayerPmd\"\"\n\005Param\022\031\n\025SelfInfoPlayerP"
      "md_C2S\020\000\"8\n\025SelfInfoPlayerPmd_C2S\022\037\n\006pla"
      "yer\030\001 \001(\0132\017.Types.P_Playerb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 154);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PlayerPmd.proto", &protobuf_RegisterTypes);
  ::protobuf_Types_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_PlayerPmd_2eproto
namespace PlatPmd {
const ::google::protobuf::EnumDescriptor* PlayerPmd_Param_descriptor() {
  protobuf_PlayerPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_PlayerPmd_2eproto::file_level_enum_descriptors[0];
}
bool PlayerPmd_Param_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const PlayerPmd_Param PlayerPmd::SelfInfoPlayerPmd_C2S;
const PlayerPmd_Param PlayerPmd::Param_MIN;
const PlayerPmd_Param PlayerPmd::Param_MAX;
const int PlayerPmd::Param_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void PlayerPmd::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PlayerPmd::PlayerPmd()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_PlayerPmd_2eproto::scc_info_PlayerPmd.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:PlatPmd.PlayerPmd)
}
PlayerPmd::PlayerPmd(const PlayerPmd& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:PlatPmd.PlayerPmd)
}

void PlayerPmd::SharedCtor() {
}

PlayerPmd::~PlayerPmd() {
  // @@protoc_insertion_point(destructor:PlatPmd.PlayerPmd)
  SharedDtor();
}

void PlayerPmd::SharedDtor() {
}

void PlayerPmd::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PlayerPmd::descriptor() {
  ::protobuf_PlayerPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_PlayerPmd_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PlayerPmd& PlayerPmd::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_PlayerPmd_2eproto::scc_info_PlayerPmd.base);
  return *internal_default_instance();
}


void PlayerPmd::Clear() {
// @@protoc_insertion_point(message_clear_start:PlatPmd.PlayerPmd)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool PlayerPmd::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PlatPmd.PlayerPmd)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:PlatPmd.PlayerPmd)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PlatPmd.PlayerPmd)
  return false;
#undef DO_
}

void PlayerPmd::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PlatPmd.PlayerPmd)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PlatPmd.PlayerPmd)
}

::google::protobuf::uint8* PlayerPmd::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PlatPmd.PlayerPmd)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PlatPmd.PlayerPmd)
  return target;
}

size_t PlayerPmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PlatPmd.PlayerPmd)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PlayerPmd::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PlatPmd.PlayerPmd)
  GOOGLE_DCHECK_NE(&from, this);
  const PlayerPmd* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PlayerPmd>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PlatPmd.PlayerPmd)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PlatPmd.PlayerPmd)
    MergeFrom(*source);
  }
}

void PlayerPmd::MergeFrom(const PlayerPmd& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PlatPmd.PlayerPmd)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void PlayerPmd::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PlatPmd.PlayerPmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PlayerPmd::CopyFrom(const PlayerPmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PlatPmd.PlayerPmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerPmd::IsInitialized() const {
  return true;
}

void PlayerPmd::Swap(PlayerPmd* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PlayerPmd::InternalSwap(PlayerPmd* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PlayerPmd::GetMetadata() const {
  protobuf_PlayerPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_PlayerPmd_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SelfInfoPlayerPmd_C2S::InitAsDefaultInstance() {
  ::PlatPmd::_SelfInfoPlayerPmd_C2S_default_instance_._instance.get_mutable()->player_ = const_cast< ::Types::P_Player*>(
      ::Types::P_Player::internal_default_instance());
}
void SelfInfoPlayerPmd_C2S::clear_player() {
  if (GetArenaNoVirtual() == NULL && player_ != NULL) {
    delete player_;
  }
  player_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SelfInfoPlayerPmd_C2S::kPlayerFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SelfInfoPlayerPmd_C2S::SelfInfoPlayerPmd_C2S()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_PlayerPmd_2eproto::scc_info_SelfInfoPlayerPmd_C2S.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:PlatPmd.SelfInfoPlayerPmd_C2S)
}
SelfInfoPlayerPmd_C2S::SelfInfoPlayerPmd_C2S(const SelfInfoPlayerPmd_C2S& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_player()) {
    player_ = new ::Types::P_Player(*from.player_);
  } else {
    player_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:PlatPmd.SelfInfoPlayerPmd_C2S)
}

void SelfInfoPlayerPmd_C2S::SharedCtor() {
  player_ = NULL;
}

SelfInfoPlayerPmd_C2S::~SelfInfoPlayerPmd_C2S() {
  // @@protoc_insertion_point(destructor:PlatPmd.SelfInfoPlayerPmd_C2S)
  SharedDtor();
}

void SelfInfoPlayerPmd_C2S::SharedDtor() {
  if (this != internal_default_instance()) delete player_;
}

void SelfInfoPlayerPmd_C2S::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SelfInfoPlayerPmd_C2S::descriptor() {
  ::protobuf_PlayerPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_PlayerPmd_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SelfInfoPlayerPmd_C2S& SelfInfoPlayerPmd_C2S::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_PlayerPmd_2eproto::scc_info_SelfInfoPlayerPmd_C2S.base);
  return *internal_default_instance();
}


void SelfInfoPlayerPmd_C2S::Clear() {
// @@protoc_insertion_point(message_clear_start:PlatPmd.SelfInfoPlayerPmd_C2S)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && player_ != NULL) {
    delete player_;
  }
  player_ = NULL;
  _internal_metadata_.Clear();
}

bool SelfInfoPlayerPmd_C2S::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PlatPmd.SelfInfoPlayerPmd_C2S)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Types.P_Player player = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_player()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PlatPmd.SelfInfoPlayerPmd_C2S)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PlatPmd.SelfInfoPlayerPmd_C2S)
  return false;
#undef DO_
}

void SelfInfoPlayerPmd_C2S::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PlatPmd.SelfInfoPlayerPmd_C2S)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Types.P_Player player = 1;
  if (this->has_player()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_player(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PlatPmd.SelfInfoPlayerPmd_C2S)
}

::google::protobuf::uint8* SelfInfoPlayerPmd_C2S::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PlatPmd.SelfInfoPlayerPmd_C2S)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Types.P_Player player = 1;
  if (this->has_player()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_player(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PlatPmd.SelfInfoPlayerPmd_C2S)
  return target;
}

size_t SelfInfoPlayerPmd_C2S::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PlatPmd.SelfInfoPlayerPmd_C2S)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .Types.P_Player player = 1;
  if (this->has_player()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *player_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SelfInfoPlayerPmd_C2S::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PlatPmd.SelfInfoPlayerPmd_C2S)
  GOOGLE_DCHECK_NE(&from, this);
  const SelfInfoPlayerPmd_C2S* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SelfInfoPlayerPmd_C2S>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PlatPmd.SelfInfoPlayerPmd_C2S)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PlatPmd.SelfInfoPlayerPmd_C2S)
    MergeFrom(*source);
  }
}

void SelfInfoPlayerPmd_C2S::MergeFrom(const SelfInfoPlayerPmd_C2S& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PlatPmd.SelfInfoPlayerPmd_C2S)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_player()) {
    mutable_player()->::Types::P_Player::MergeFrom(from.player());
  }
}

void SelfInfoPlayerPmd_C2S::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PlatPmd.SelfInfoPlayerPmd_C2S)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SelfInfoPlayerPmd_C2S::CopyFrom(const SelfInfoPlayerPmd_C2S& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PlatPmd.SelfInfoPlayerPmd_C2S)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SelfInfoPlayerPmd_C2S::IsInitialized() const {
  return true;
}

void SelfInfoPlayerPmd_C2S::Swap(SelfInfoPlayerPmd_C2S* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SelfInfoPlayerPmd_C2S::InternalSwap(SelfInfoPlayerPmd_C2S* other) {
  using std::swap;
  swap(player_, other->player_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SelfInfoPlayerPmd_C2S::GetMetadata() const {
  protobuf_PlayerPmd_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_PlayerPmd_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace PlatPmd
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::PlatPmd::PlayerPmd* Arena::CreateMaybeMessage< ::PlatPmd::PlayerPmd >(Arena* arena) {
  return Arena::CreateInternal< ::PlatPmd::PlayerPmd >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::PlatPmd::SelfInfoPlayerPmd_C2S* Arena::CreateMaybeMessage< ::PlatPmd::SelfInfoPlayerPmd_C2S >(Arena* arena) {
  return Arena::CreateInternal< ::PlatPmd::SelfInfoPlayerPmd_C2S >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
