// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

#ifndef PROTOBUF_INCLUDED_player_2eproto
#define PROTOBUF_INCLUDED_player_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "type.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_player_2eproto 

namespace protobuf_player_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_player_2eproto
namespace section {
class self_info_s2c;
class self_info_s2cDefaultTypeInternal;
extern self_info_s2cDefaultTypeInternal _self_info_s2c_default_instance_;
}  // namespace section
namespace google {
namespace protobuf {
template<> ::section::self_info_s2c* Arena::CreateMaybeMessage<::section::self_info_s2c>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace section {

// ===================================================================

class self_info_s2c : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:section.self_info_s2c) */ {
 public:
  self_info_s2c();
  virtual ~self_info_s2c();

  self_info_s2c(const self_info_s2c& from);

  inline self_info_s2c& operator=(const self_info_s2c& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  self_info_s2c(self_info_s2c&& from) noexcept
    : self_info_s2c() {
    *this = ::std::move(from);
  }

  inline self_info_s2c& operator=(self_info_s2c&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const self_info_s2c& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const self_info_s2c* internal_default_instance() {
    return reinterpret_cast<const self_info_s2c*>(
               &_self_info_s2c_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(self_info_s2c* other);
  friend void swap(self_info_s2c& a, self_info_s2c& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline self_info_s2c* New() const final {
    return CreateMaybeMessage<self_info_s2c>(NULL);
  }

  self_info_s2c* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<self_info_s2c>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const self_info_s2c& from);
  void MergeFrom(const self_info_s2c& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(self_info_s2c* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .types.p_player player = 1;
  bool has_player() const;
  void clear_player();
  static const int kPlayerFieldNumber = 1;
  private:
  const ::types::p_player& _internal_player() const;
  public:
  const ::types::p_player& player() const;
  ::types::p_player* release_player();
  ::types::p_player* mutable_player();
  void set_allocated_player(::types::p_player* player);

  // @@protoc_insertion_point(class_scope:section.self_info_s2c)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::types::p_player* player_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_player_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// self_info_s2c

// .types.p_player player = 1;
inline bool self_info_s2c::has_player() const {
  return this != internal_default_instance() && player_ != NULL;
}
inline const ::types::p_player& self_info_s2c::_internal_player() const {
  return *player_;
}
inline const ::types::p_player& self_info_s2c::player() const {
  const ::types::p_player* p = player_;
  // @@protoc_insertion_point(field_get:section.self_info_s2c.player)
  return p != NULL ? *p : *reinterpret_cast<const ::types::p_player*>(
      &::types::_p_player_default_instance_);
}
inline ::types::p_player* self_info_s2c::release_player() {
  // @@protoc_insertion_point(field_release:section.self_info_s2c.player)
  
  ::types::p_player* temp = player_;
  player_ = NULL;
  return temp;
}
inline ::types::p_player* self_info_s2c::mutable_player() {
  
  if (player_ == NULL) {
    auto* p = CreateMaybeMessage<::types::p_player>(GetArenaNoVirtual());
    player_ = p;
  }
  // @@protoc_insertion_point(field_mutable:section.self_info_s2c.player)
  return player_;
}
inline void self_info_s2c::set_allocated_player(::types::p_player* player) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(player_);
  }
  if (player) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      player = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, player, submessage_arena);
    }
    
  } else {
    
  }
  player_ = player;
  // @@protoc_insertion_point(field_set_allocated:section.self_info_s2c.player)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace section

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_player_2eproto
