// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

#include "player.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_type_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_type_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_p_player;
}  // namespace protobuf_type_2eproto
namespace section {
class self_info_s2cDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<self_info_s2c>
      _instance;
} _self_info_s2c_default_instance_;
}  // namespace section
namespace protobuf_player_2eproto {
static void InitDefaultsself_info_s2c() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::section::_self_info_s2c_default_instance_;
    new (ptr) ::section::self_info_s2c();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::section::self_info_s2c::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_self_info_s2c =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsself_info_s2c}, {
      &protobuf_type_2eproto::scc_info_p_player.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_self_info_s2c.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::self_info_s2c, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::section::self_info_s2c, player_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::section::self_info_s2c)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::section::_self_info_s2c_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "player.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014player.proto\022\007section\032\ntype.proto\"0\n\rs"
      "elf_info_s2c\022\037\n\006player\030\001 \001(\0132\017.types.p_p"
      "layerb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 93);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "player.proto", &protobuf_RegisterTypes);
  ::protobuf_type_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_player_2eproto
namespace section {

// ===================================================================

void self_info_s2c::InitAsDefaultInstance() {
  ::section::_self_info_s2c_default_instance_._instance.get_mutable()->player_ = const_cast< ::types::p_player*>(
      ::types::p_player::internal_default_instance());
}
void self_info_s2c::clear_player() {
  if (GetArenaNoVirtual() == NULL && player_ != NULL) {
    delete player_;
  }
  player_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int self_info_s2c::kPlayerFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

self_info_s2c::self_info_s2c()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_player_2eproto::scc_info_self_info_s2c.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:section.self_info_s2c)
}
self_info_s2c::self_info_s2c(const self_info_s2c& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_player()) {
    player_ = new ::types::p_player(*from.player_);
  } else {
    player_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:section.self_info_s2c)
}

void self_info_s2c::SharedCtor() {
  player_ = NULL;
}

self_info_s2c::~self_info_s2c() {
  // @@protoc_insertion_point(destructor:section.self_info_s2c)
  SharedDtor();
}

void self_info_s2c::SharedDtor() {
  if (this != internal_default_instance()) delete player_;
}

void self_info_s2c::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* self_info_s2c::descriptor() {
  ::protobuf_player_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_player_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const self_info_s2c& self_info_s2c::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_player_2eproto::scc_info_self_info_s2c.base);
  return *internal_default_instance();
}


void self_info_s2c::Clear() {
// @@protoc_insertion_point(message_clear_start:section.self_info_s2c)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && player_ != NULL) {
    delete player_;
  }
  player_ = NULL;
  _internal_metadata_.Clear();
}

bool self_info_s2c::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:section.self_info_s2c)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .types.p_player player = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_player()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:section.self_info_s2c)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:section.self_info_s2c)
  return false;
#undef DO_
}

void self_info_s2c::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:section.self_info_s2c)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .types.p_player player = 1;
  if (this->has_player()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_player(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:section.self_info_s2c)
}

::google::protobuf::uint8* self_info_s2c::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:section.self_info_s2c)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .types.p_player player = 1;
  if (this->has_player()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_player(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:section.self_info_s2c)
  return target;
}

size_t self_info_s2c::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:section.self_info_s2c)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .types.p_player player = 1;
  if (this->has_player()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *player_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void self_info_s2c::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:section.self_info_s2c)
  GOOGLE_DCHECK_NE(&from, this);
  const self_info_s2c* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const self_info_s2c>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:section.self_info_s2c)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:section.self_info_s2c)
    MergeFrom(*source);
  }
}

void self_info_s2c::MergeFrom(const self_info_s2c& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:section.self_info_s2c)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_player()) {
    mutable_player()->::types::p_player::MergeFrom(from.player());
  }
}

void self_info_s2c::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:section.self_info_s2c)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void self_info_s2c::CopyFrom(const self_info_s2c& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:section.self_info_s2c)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool self_info_s2c::IsInitialized() const {
  return true;
}

void self_info_s2c::Swap(self_info_s2c* other) {
  if (other == this) return;
  InternalSwap(other);
}
void self_info_s2c::InternalSwap(self_info_s2c* other) {
  using std::swap;
  swap(player_, other->player_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata self_info_s2c::GetMetadata() const {
  protobuf_player_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_player_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace section
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::section::self_info_s2c* Arena::CreateMaybeMessage< ::section::self_info_s2c >(Arena* arena) {
  return Arena::CreateInternal< ::section::self_info_s2c >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
