// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Types.proto

#ifndef PROTOBUF_INCLUDED_Types_2eproto
#define PROTOBUF_INCLUDED_Types_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_Types_2eproto 

namespace protobuf_Types_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_Types_2eproto
namespace Types {
class P_Player;
class P_PlayerDefaultTypeInternal;
extern P_PlayerDefaultTypeInternal _P_Player_default_instance_;
}  // namespace Types
namespace google {
namespace protobuf {
template<> ::Types::P_Player* Arena::CreateMaybeMessage<::Types::P_Player>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Types {

// ===================================================================

class P_Player : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Types.P_Player) */ {
 public:
  P_Player();
  virtual ~P_Player();

  P_Player(const P_Player& from);

  inline P_Player& operator=(const P_Player& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  P_Player(P_Player&& from) noexcept
    : P_Player() {
    *this = ::std::move(from);
  }

  inline P_Player& operator=(P_Player&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const P_Player& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const P_Player* internal_default_instance() {
    return reinterpret_cast<const P_Player*>(
               &_P_Player_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(P_Player* other);
  friend void swap(P_Player& a, P_Player& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline P_Player* New() const final {
    return CreateMaybeMessage<P_Player>(NULL);
  }

  P_Player* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<P_Player>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const P_Player& from);
  void MergeFrom(const P_Player& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P_Player* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string head_img = 4;
  void clear_head_img();
  static const int kHeadImgFieldNumber = 4;
  const ::std::string& head_img() const;
  void set_head_img(const ::std::string& value);
  #if LANG_CXX11
  void set_head_img(::std::string&& value);
  #endif
  void set_head_img(const char* value);
  void set_head_img(const char* value, size_t size);
  ::std::string* mutable_head_img();
  ::std::string* release_head_img();
  void set_allocated_head_img(::std::string* head_img);

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // int32 sex = 3;
  void clear_sex();
  static const int kSexFieldNumber = 3;
  ::google::protobuf::int32 sex() const;
  void set_sex(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Types.P_Player)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr head_img_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 sex_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Types_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// P_Player

// int32 id = 1;
inline void P_Player::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 P_Player::id() const {
  // @@protoc_insertion_point(field_get:Types.P_Player.id)
  return id_;
}
inline void P_Player::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Types.P_Player.id)
}

// string name = 2;
inline void P_Player::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& P_Player::name() const {
  // @@protoc_insertion_point(field_get:Types.P_Player.name)
  return name_.GetNoArena();
}
inline void P_Player::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Types.P_Player.name)
}
#if LANG_CXX11
inline void P_Player::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Types.P_Player.name)
}
#endif
inline void P_Player::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Types.P_Player.name)
}
inline void P_Player::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Types.P_Player.name)
}
inline ::std::string* P_Player::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:Types.P_Player.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* P_Player::release_name() {
  // @@protoc_insertion_point(field_release:Types.P_Player.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void P_Player::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Types.P_Player.name)
}

// int32 sex = 3;
inline void P_Player::clear_sex() {
  sex_ = 0;
}
inline ::google::protobuf::int32 P_Player::sex() const {
  // @@protoc_insertion_point(field_get:Types.P_Player.sex)
  return sex_;
}
inline void P_Player::set_sex(::google::protobuf::int32 value) {
  
  sex_ = value;
  // @@protoc_insertion_point(field_set:Types.P_Player.sex)
}

// string head_img = 4;
inline void P_Player::clear_head_img() {
  head_img_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& P_Player::head_img() const {
  // @@protoc_insertion_point(field_get:Types.P_Player.head_img)
  return head_img_.GetNoArena();
}
inline void P_Player::set_head_img(const ::std::string& value) {
  
  head_img_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Types.P_Player.head_img)
}
#if LANG_CXX11
inline void P_Player::set_head_img(::std::string&& value) {
  
  head_img_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Types.P_Player.head_img)
}
#endif
inline void P_Player::set_head_img(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  head_img_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Types.P_Player.head_img)
}
inline void P_Player::set_head_img(const char* value, size_t size) {
  
  head_img_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Types.P_Player.head_img)
}
inline ::std::string* P_Player::mutable_head_img() {
  
  // @@protoc_insertion_point(field_mutable:Types.P_Player.head_img)
  return head_img_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* P_Player::release_head_img() {
  // @@protoc_insertion_point(field_release:Types.P_Player.head_img)
  
  return head_img_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void P_Player::set_allocated_head_img(::std::string* head_img) {
  if (head_img != NULL) {
    
  } else {
    
  }
  head_img_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), head_img);
  // @@protoc_insertion_point(field_set_allocated:Types.P_Player.head_img)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Types

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_Types_2eproto
