// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

#ifndef PROTOBUF_INCLUDED_type_2eproto
#define PROTOBUF_INCLUDED_type_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_type_2eproto 

namespace protobuf_type_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_type_2eproto
namespace types {
class p_player;
class p_playerDefaultTypeInternal;
extern p_playerDefaultTypeInternal _p_player_default_instance_;
}  // namespace types
namespace google {
namespace protobuf {
template<> ::types::p_player* Arena::CreateMaybeMessage<::types::p_player>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace types {

// ===================================================================

class p_player : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:types.p_player) */ {
 public:
  p_player();
  virtual ~p_player();

  p_player(const p_player& from);

  inline p_player& operator=(const p_player& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  p_player(p_player&& from) noexcept
    : p_player() {
    *this = ::std::move(from);
  }

  inline p_player& operator=(p_player&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const p_player& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const p_player* internal_default_instance() {
    return reinterpret_cast<const p_player*>(
               &_p_player_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(p_player* other);
  friend void swap(p_player& a, p_player& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline p_player* New() const final {
    return CreateMaybeMessage<p_player>(NULL);
  }

  p_player* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<p_player>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const p_player& from);
  void MergeFrom(const p_player& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(p_player* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string head_img = 4;
  void clear_head_img();
  static const int kHeadImgFieldNumber = 4;
  const ::std::string& head_img() const;
  void set_head_img(const ::std::string& value);
  #if LANG_CXX11
  void set_head_img(::std::string&& value);
  #endif
  void set_head_img(const char* value);
  void set_head_img(const char* value, size_t size);
  ::std::string* mutable_head_img();
  ::std::string* release_head_img();
  void set_allocated_head_img(::std::string* head_img);

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // int32 sex = 3;
  void clear_sex();
  static const int kSexFieldNumber = 3;
  ::google::protobuf::int32 sex() const;
  void set_sex(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:types.p_player)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr head_img_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 sex_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_type_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// p_player

// int32 id = 1;
inline void p_player::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 p_player::id() const {
  // @@protoc_insertion_point(field_get:types.p_player.id)
  return id_;
}
inline void p_player::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:types.p_player.id)
}

// string name = 2;
inline void p_player::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& p_player::name() const {
  // @@protoc_insertion_point(field_get:types.p_player.name)
  return name_.GetNoArena();
}
inline void p_player::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:types.p_player.name)
}
#if LANG_CXX11
inline void p_player::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:types.p_player.name)
}
#endif
inline void p_player::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:types.p_player.name)
}
inline void p_player::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:types.p_player.name)
}
inline ::std::string* p_player::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:types.p_player.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* p_player::release_name() {
  // @@protoc_insertion_point(field_release:types.p_player.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void p_player::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:types.p_player.name)
}

// int32 sex = 3;
inline void p_player::clear_sex() {
  sex_ = 0;
}
inline ::google::protobuf::int32 p_player::sex() const {
  // @@protoc_insertion_point(field_get:types.p_player.sex)
  return sex_;
}
inline void p_player::set_sex(::google::protobuf::int32 value) {
  
  sex_ = value;
  // @@protoc_insertion_point(field_set:types.p_player.sex)
}

// string head_img = 4;
inline void p_player::clear_head_img() {
  head_img_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& p_player::head_img() const {
  // @@protoc_insertion_point(field_get:types.p_player.head_img)
  return head_img_.GetNoArena();
}
inline void p_player::set_head_img(const ::std::string& value) {
  
  head_img_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:types.p_player.head_img)
}
#if LANG_CXX11
inline void p_player::set_head_img(::std::string&& value) {
  
  head_img_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:types.p_player.head_img)
}
#endif
inline void p_player::set_head_img(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  head_img_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:types.p_player.head_img)
}
inline void p_player::set_head_img(const char* value, size_t size) {
  
  head_img_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:types.p_player.head_img)
}
inline ::std::string* p_player::mutable_head_img() {
  
  // @@protoc_insertion_point(field_mutable:types.p_player.head_img)
  return head_img_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* p_player::release_head_img() {
  // @@protoc_insertion_point(field_release:types.p_player.head_img)
  
  return head_img_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void p_player::set_allocated_head_img(::std::string* head_img) {
  if (head_img != NULL) {
    
  } else {
    
  }
  head_img_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), head_img);
  // @@protoc_insertion_point(field_set_allocated:types.p_player.head_img)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace types

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_type_2eproto
